# Generated by Django 4.1.4 on 2023-01-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
