# Generated by Django 4.1.4 on 2023-01-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0010_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
        migrations.AddField(
            model_name='book',
            name='slug1',
            field=models.SlugField(default=''),
        ),
    ]
