# Generated by Django 4.1.4 on 2023-01-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0011_remove_book_slug_book_slug1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='slug1',
            new_name='slug',
        ),
    ]
